import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Patrick Korhonen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="fixed top-0 left-0">
          <NavBar />
          </div>
          <div className="h-screen mt-16">{children}</div>
        </div>
      </body>
    </html>
  );
}
